[pytest]
testpaths = horse_racing/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# テストの詳細を表示とカバレッジ測定の設定
addopts = -v --tb=short --cov=horse_racing --cov-report=term-missing

# テストカバレッジの設定
[coverage:run]
source = .
omit =
    horse_racing/tests/*
    venv/*
    setup.py

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise NotImplementedError
    if __name__ == .__main__.:
    pass